name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # Run "bundle install", and cache the result automatically.
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Run RSpec
        run: bundle exec rspec
